---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    db: postgres
spec:
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.2-alpine
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            cpu: 100m
            memory: 60Mi
          limits:
            cpu: 200m
            memory: 120Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
      volumes:
      - name: postgresql-data
        emptyDir: {} 

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    db: postgres
spec:
  type: ClusterIP
  selector:
    db: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
