---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    db: redis
spec:
  selector:
    matchLabels:
      db: redis
  template:
    metadata:
      labels:
        db: redis
    spec:
      containers:
      - name: redis
        image: docker.io/redis/redis-stack-server:7.2.0-v8
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {} 

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    db: redis
spec:
  type: ClusterIP
  selector:
    db: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
