---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: results-statestore
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: keyPrefix
    value: name 
  - name: connectionString
    value: "host=postgres user=postgres password=postgres port=5432 connect_timeout=10"
  